EPAM, NodeJS practice, Homework3
grechintanya/nodeJS_practice pull request #3
Opened 2023-10-23 13:22 UTC by grechintanya

2023-11-01 14:32 UTC, VitalyaIlin requested changes

2023-11-01 14:32 UTC, VitalyaIlin commented on src/config/DBconnect.ts
> +const DATABASE_URI =
it's better you use .env file for this variable

2023-11-01 14:32 UTC, VitalyaIlin commented on src/controllers/genresControllers.ts
> +      return res.status(404).json({ message: 'Genre not found' });
Handle such errors in global error handling middleware

2023-11-01 14:32 UTC, VitalyaIlin commented on src/server.ts
>    res.status(500).send('Something went wrong');
Handle all types of errors in this middleware, 404, 422 etc.

2023-11-01 14:32 UTC, VitalyaIlin commented on src/controllers/moviesControllers.ts
> +    const savedMovie = (await Movie.create(newMovie)).toObject();
Why do you need .toObject() call here?

2023-11-01 14:32 UTC, VitalyaIlin commented on src/controllers/genresControllers.ts
> +    return res.sendStatus(204);
In such cases, it is more appropriate to send an empty array with a status code of 200
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204

2023-11-03 17:18 UTC, grechintanya commented
I've remade error handling. Please, have a look

2023-11-07 09:19 UTC, VitalyaIlin approved these changes

2023-11-07 09:39 UTC, merged